"""Add user savings_balance and user savings_interest_rate

Revision ID: 820bdea29847
Revises: b32621101610
Create Date: 2026-09-20 03:43:10.108832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820bdea29847'
down_revision = 'b32621101610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_balance', sa.Float(), nullable=False,server_default='0.0'))
        batch_op.add_column(sa.Column('savings_interest_rate', sa.Float(), nullable=False,server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('savings_interest_rate')
        batch_op.drop_column('savings_balance')

    # ### end Alembic commands ###
